name: red_rocket_test_task
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  go_router: ^16.2.0
  flutter_bloc: ^9.1.1
  bloc: ^9.0.0
  dio: ^5.9.0
  logger: ^2.6.1
  get_it: ^8.2.0
  injectable: ^2.5.1
  flutter_secure_storage: ^9.2.4
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  flutter_dotenv: ^5.2.1
  flutter_screenutil: ^5.9.3
  equatable: ^2.0.7
  reactive_forms: ^18.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.14
  freezed: ^2.5.8
  json_serializable: ^6.9.4
  injectable_generator: ^2.6.1

flutter:
  uses-material-design: true